### ISSUE TITLE
发现木马

### ISSUE THREAD

**Issue by cospider** [ansiboy/ChiTuStore#1]
![1](https://cloud.githubusercontent.com/assets/16320745/18426974/e32338c2-78f7-11e6-82c9-b6e29ecdca28.png)
![2](https://cloud.githubusercontent.com/assets/16320745/18426975/e3253186-78f7-11e6-83b2-e13fcaa9b14d.png)

**Comment by ansiboy** [comment]
确定是木马？不是虚报的？

**Comment by cospider** [comment]
android studio以前没用过，应该是腾讯管家的误报。
